### PR TITLE
Allow additional paths in lessOptions

### PR DESCRIPTION
**Pull request by whitecolor**
https://github.com/stealjs/steal/issues/372

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks for submitting. Can you give an example of what this would allow you to do that you couldn't previously do? I think it's a fair change, just want to understand what this allows now.

**Comment by whitecolor** [comment]
In my less files I use absolute paths

Say I have `styles` directory where I put common imports files for my project, and then in any file I just include:

```less
@import "/styles/some/common.less"
```

So one maysay: use relative, it is better not to use absolute paths and so on... but currently it is more appropriate for my flow to use such paths. I dont have to care about where my particular file (with `@import` statement) is located. I just put absolute path there. and it works fine. if it would be absolutly no need in this option for user, it would be probably removed from `less/css` compiler. So I think you should allow users to define it. And even more I would include `baseURL` dir in `paths` by default, for convinice, I will break nothing but will demand less config from user the whant to use `absolute` urls (wich are actually relative to baseURL dir).

**Comment by matthewp** [comment]
Thanks for the explanation, will review the code and issue tomorrow (been a while since I thought about less path rules).

**Comment by matthewp** [comment]
Looks good to me, if you can update the PR towards the `minor` branch I'll merge it.  It can go in 0.9.0 as a new feature.

**Comment by matthewp** [comment]
Merged in minor in #378

**Pull request closed without merging**
