### PR TITLE
Improve the error message when steal-less is not installed

### LINKED ISSUE #995: Improve the error message when steal-less isn’t installed
While upgrading [a project](https://github.com/donejs/donejs-number-input) to StealJS 1, I ran my build before installing `steal-less` and got this error:

```
Error: Error loading "donejs-number-input@0.1.1#donejs-number-input.less!less" at <unknown>
Error loading "donejs-number-input@0.1.1#donejs-number-input.less!less" from "donejs-number-input@0.1.1#donejs-number-input" at file:/Library/WebServer/Documents/donejs-number-input/src/donejs-number-input.js
Error loading "less" at file:/Library/WebServer/Documents/donejs-number-input/less.js
ENOENT: no such file or directory, open '/Library/WebServer/Documents/donejs-number-input/less.js'
    at Error (native)
```

For plugins that were previously included in StealJS, it’d be nice if the error messages were more friendly and either:
1) Included a link to [the docs that explain the issue](http://stealjs.com/docs/StealJS.topics.migrating-one.html#css-and-less-plugins).
2) Included the exact instructions in the error.
3) Offered to fix the issue for me (in my case, by installing `steal-less` and updating my `package.json` with the `plugins` configuration).

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #995

screen shot 2017-08-01 at 09 26 07

### CODE REVIEW

**Comment by m-mujica** [comment]
@chasenlehara any feedback on the error message wording?

**Comment by m-mujica** [comment]
@chasenlehara the message is only in `src/core`, in the diff it appears in multiple places because Grunt will update some concatenated files...

or do you mean having like a global file/spot with all error messages?

**Comment by chasenlehara** [comment]
@m-mujica Gotcha, I didn’t know this repo included built files. I don’t think it’s necessary to keep all the error messages in one file.

**Comment by matthewp** [comment]
giphy

**Pull request merged**
