### PR TITLE
adding steal-clone

### PR DESCRIPTION
**Pull request by phillipskevin**
Depends on https://github.com/stealjs/system-npm/pull/112, https://github.com/stealjs/system-trace/pull/13.

Closes https://github.com/stealjs/steal/issues/509.

### CODE REVIEW

**Comment by matthewp** [comment]
Any ideas why Travis is failing?

**Comment by phillipskevin** [comment]
It's just failing because it needs the system-npm and system-trace changes that haven't been merged yet.

**Comment by matthewp** [comment]
Ok, can you link to those prs here?

**Comment by phillipskevin** [comment]
will re-open against master

**Pull request closed without merging**
