### PR TITLE
warning user when 'main' is not set in production environment

### PR DESCRIPTION
**Pull request by phillipskevin**
Closes https://github.com/stealjs/steal/issues/537.

I'm throwing an error since `console.warn` calls will be removed from `steal.production.js`. Let me know if you want me to handle this some other way.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
I don't think we should throw. It's possible that the main might by dynamically imported based on something in the page. 

You can be tricky and do something like:

var warn = console.warn

warn.call(console, ...)

**Comment by phillipskevin** [comment]
@justinbmeyer I updated the PR to do it that way. Thanks.

**Comment by matthewp** [comment]
I think IE8 doesn't support console.warn, or only supports it if the devtools are open, not sure which, should probably account for that.

**Comment by phillipskevin** [comment]
@matthewp IE8 creates the `console` object after devtools are opened. I changed the code to `var warn = console && console.warn || function() {};`. There are a few other `console.log` statements that also won't work in IE8; should I put in a new issue for those?

**Comment by matthewp** [comment]
Yeah, a new issue is a good idea, thanks.

**Comment by phillipskevin** [comment]
https://github.com/stealjs/steal/issues/541 is the new issue.

**Comment by matthewp** [comment]
cool, this will be in the next release, thanks.

**Pull request merged**
