### PR TITLE
Get steal-npm into core

### LINKED ISSUE #1064: Move steal-npm into core

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #1064

### CODE REVIEW

**Comment by matthewp** [comment]
The intent is for `src/` to be for stuff that gets built into steal.js. Since we don't build the npm plugin, I think we should keep it in `ext/npm.js`, etc. and just edit those files directly. So there's just the matter of putting the tests somewhere. That's a hard one to decide... but I guess `test/npm` is probably the place.

**Comment by m-mujica** [comment]
giphy

makes sense

**Comment by m-mujica** [comment]
there is already a test/npm folder, test/npm-extension maybe?

**Comment by matthewp** [comment]
We can get rid of the tets/npm tests, they were needed to test "integration" but now that it's in core that's needed. Seriously doubt they test anything that the steal-npm tests don't.

**Comment by m-mujica** [comment]
Ok @matthewp I think this is in good shape for a second review! let me know what you think.

**Comment by matthewp** [comment]
Do you know why loader.js has changes?

**Comment by m-mujica** [comment]
@matthewp I think it's the Promise shim in when.js, I didn't lock down the version to  `3.7.5` as in the es6-module-loader repo, want me to do that?

**Comment by m-mujica** [comment]
@matthewp yup, it's that, just locked down the version locally and saw the changes. Let me commit that

**Comment by matthewp** [comment]
Lgtm

**Pull request merged**
