### PR TITLE
Fixes #1108. Adds tasks to build without promise shim

### LINKED ISSUE #1108: Create a build that excludes the Promise polyfill
All modern browsers support Promises, so any projects targeting that don't need the polyfill. We could have a `steal-nopromise.js` or something like that.

http://caniuse.com/#feat=promises

### PR DESCRIPTION
**Pull request by mjstahl**
Issue:
https://github.com/stealjs/steal/issues/1108

screen shot 2017-03-21 at 10 01 21

### CODE REVIEW

**Comment by m-mujica** [comment]
@mjstahl it seems Saucelabs had issues running tests https://travis-ci.org/stealjs/steal/jobs/213422248#L1255, I'd just rebase/merge master (we changed the saucelabs script and try a new build).

**Comment by matthewp** [comment]
@mjstahl we are happy to get this in, just need a rebase :)

**Comment by matthewp** [comment]
I rebased this and put it in the stealjs branch:

https://github.com/stealjs/steal/tree/1108-build-without-promise-shim

I'd like to see a couple of basic tests for this, one that loads in dev mode and one in prod mode. The way prod mode is automatically detected makes me wonder if that needs to be updated to account for the fact that this file is named steal-sans-promises.production.js and not steal.production.js

**Comment by matthewp** [comment]
This PR is being replaced by https://github.com/stealjs/steal/pull/1179

**Pull request closed without merging**
