### PR TITLE
Multiple updates to the Contributing guide

### LINKED ISSUE #1146: Update the contributing guide to add all steps needed to run tests
The [contributing guide](http://stealjs.com/docs/guides.Contributing.html#developing-steal) should be updated to mention needing to run `npm run npm-copy` after the initial clone.  Not sure if anything else is missing.

### PR DESCRIPTION
**Pull request by m-mujica**
- Update repositories urls
- Update steps to generate the website
- Update test example to use `QUnit.test`
- Remove references to SystemJS and the es6ml
- Update explanation about StealJS code structure

Closes #1146

google chrome

### CODE REVIEW

**Comment by matthewp** [comment]
I think there should be more explanation. Running `npm test` to get everything setup and running is fine, but when developing you're going to be working on individual test pages.  So I'd add:

* An explanation to run `npm test` **first** to get everything bootstrapped.
* An explanation of how the project is structured and how to test individual parts (like the json tests being in `src/json`.  Not explaining every module just an overall explanation that gives people an idea of how to navigate.

**Comment by m-mujica** [comment]
xpjbwd

**Comment by m-mujica** [comment]
thoughts @matthewp @chasenlehara ?

**Comment by m-mujica** [comment]
seems we have a flaky test, will take a look at it next week.

0002screenshot

**Comment by matthewp** [comment]
LGTM (aside from the flaky test).

**Pull request merged**
