### PR TITLE
Add steal-less dependency.

### LINKED ISSUE #346: Move less plugin into stealjs/system-less
I've moved this issue out to stealjs/system-less#1. We should discuss anything about this issue not related to actual core steal features over there. Gonna keep this ticket open for tracking purposes.

As part of this, we should actually move the steal plugin out of this repository and out into that one and make sure it's easily installable/accessible. Perhaps we might still want to include the file in `steal` releases, as well?

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #346.

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp have you had a chance to review this PR? wondering if it's ok, needs to be rebased though.

**Comment by matthewp** [comment]
Yeah it's ok, just hadn't merged it.  Sorry, if you rebase I can merge it.

**Comment by m-mujica** [comment]
@matthewp done! it was just a small conflict in the package.json.

**Comment by m-mujica** [comment]
=( appveyor failed, it seems to be an issue with npm install, can you please re-run the build? thanks

**Pull request merged**
