### PR TITLE
steal object and url-options merged into one config object

### PR DESCRIPTION
**Pull request by pYr0x**
related to https://github.com/stealjs/steal/issues/630 

the config on startup is now merged 
```
config = extend(config, urlOptions);
```

url-options is the source of truth

### CODE REVIEW

**Comment by matthewp** [comment]
Is there a scenario where this is needed?  I think the only time "config" exists is during the build or no?

**Comment by pYr0x** [comment]
@matthewp this PR is not a priority fix.

with this fix we prevent call `System.config();` twice which can cause unknown side effects.

`config` also exits if we have a `steal` object

**Comment by pYr0x** [comment]
this PR solved 2 problems:
1. now run `System.config(config);` only once. the config are now merged. before, we run the config setter twice which overwrites some configs. this solves  #631. the test covers that, that the `config-path` will be overwritten.
2. now with the merged config setting, the URL-options wins against the `steal` object.

@matthewp can you please make a steal.production again.

**Comment by matthewp** [comment]
You are amazing @pYr0x, will merge this tomorrow, but I've made it a rule not to do releases on fridays so ping me on Monday and i'll do a patch then.

**Comment by pYr0x** [comment]
@matthewp push...

**Comment by matthewp** [comment]
What do you mean?

**Comment by pYr0x** [comment]
this branch stealjs:urloptions-source-of-truth is never pushed into master?

**Comment by matthewp** [comment]
Oh. Why are you not pointing your PRs to master?

**Comment by pYr0x** [comment]
.. good question... i will now start to working on stealjs repo not on my fork... future PR will against master :)

**Comment by matthewp** [comment]
cool, if you prefer to work on your fork you can still submit the PR against master

**Pull request merged**
