### PR TITLE
Fixing typo in 0.14 changelog

### PR DESCRIPTION
**Pull request by phillipskevin**

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks

**Comment by matthewp** [comment]
This should be in the markdown file, not the gh-pages branch.

**Comment by phillipskevin** [comment]
Oh, duh. I'll submit a new PR.

**Comment by matthewp** [comment]
I went ahead and took care of it https://github.com/stealjs/steal/commit/5b48924ac12c3c247840a8cf46dc68f744ade8e5

**Comment by phillipskevin** [comment]
Thanks.

**Pull request closed without merging**
